var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!',
    mockUsers: [{
      "id": 1,
      "first_name": "Beverly",
      "last_name": "Gilbert",
      "email": "bgilbert0@networkadvertising.org",
      "gender": "Female",
      "ip_address": "253.28.135.14",
      "avatar": "https://robohash.org/ipsamullamqui.png?size=318x180&set=set1"
    }, {
      "id": 2,
      "first_name": "Joe",
      "last_name": "Daniels",
      "email": "jdaniels1@scientificamerican.com",
      "gender": "Male",
      "ip_address": "16.4.36.180",
      "avatar": "https://robohash.org/doloremtemporibuserror.png?size=318x180&set=set1"
    }, {
      "id": 3,
      "first_name": "Andrea",
      "last_name": "Rogers",
      "email": "arogers2@paginegialle.it",
      "gender": "Female",
      "ip_address": "42.193.141.56",
      "avatar": "https://robohash.org/mollitiaatsoluta.png?size=318x180&set=set1"
    }, {
      "id": 4,
      "first_name": "Dorothy",
      "last_name": "Harvey",
      "email": "dharvey3@chronoengine.com",
      "gender": "Female",
      "ip_address": "175.103.205.100",
      "avatar": "https://robohash.org/consequaturvoluptatemut.png?size=318x180&set=set1"
    }, {
      "id": 5,
      "first_name": "Ann",
      "last_name": "Hart",
      "email": "ahart4@google.cn",
      "gender": "Female",
      "ip_address": "3.50.143.54",
      "avatar": "https://robohash.org/velittemporeet.png?size=318x180&set=set1"
    }, {
      "id": 6,
      "first_name": "Douglas",
      "last_name": "Scott",
      "email": "dscott5@hugedomains.com",
      "gender": "Male",
      "ip_address": "45.81.134.183",
      "avatar": "https://robohash.org/assumendaetdolor.png?size=318x180&set=set1"
    }, {
      "id": 7,
      "first_name": "Juan",
      "last_name": "Woods",
      "email": "jwoods6@tinypic.com",
      "gender": "Male",
      "ip_address": "37.65.246.6",
      "avatar": "https://robohash.org/evenietquienim.png?size=318x180&set=set1"
    }, {
      "id": 8,
      "first_name": "Nicholas",
      "last_name": "Robinson",
      "email": "nrobinson7@cornell.edu",
      "gender": "Male",
      "ip_address": "216.164.81.58",
      "avatar": "https://robohash.org/abrepellendusnihil.png?size=318x180&set=set1"
    }, {
      "id": 9,
      "first_name": "Dorothy",
      "last_name": "Fuller",
      "email": "dfuller8@1und1.de",
      "gender": "Female",
      "ip_address": "192.204.8.165",
      "avatar": "https://robohash.org/inventorequaeratione.png?size=318x180&set=set1"
    }, {
      "id": 10,
      "first_name": "Clarence",
      "last_name": "Cox",
      "email": "ccox9@istockphoto.com",
      "gender": "Male",
      "ip_address": "32.60.225.199",
      "avatar": "https://robohash.org/voluptatemveldelectus.png?size=318x180&set=set1"
    }, {
      "id": 11,
      "first_name": "Peter",
      "last_name": "Porter",
      "email": "pportera@ox.ac.uk",
      "gender": "Male",
      "ip_address": "0.190.205.224",
      "avatar": "https://robohash.org/sequinesciunteos.png?size=318x180&set=set1"
    }, {
      "id": 12,
      "first_name": "Lillian",
      "last_name": "Murphy",
      "email": "lmurphyb@indiatimes.com",
      "gender": "Female",
      "ip_address": "193.65.85.1",
      "avatar": "https://robohash.org/debitisquisquampariatur.png?size=318x180&set=set1"
    }, {
      "id": 13,
      "first_name": "Justin",
      "last_name": "Lewis",
      "email": "jlewisc@webeden.co.uk",
      "gender": "Male",
      "ip_address": "13.181.122.166",
      "avatar": "https://robohash.org/voluptatesnemototam.png?size=318x180&set=set1"
    }, {
      "id": 14,
      "first_name": "Heather",
      "last_name": "Hart",
      "email": "hhartd@trellian.com",
      "gender": "Female",
      "ip_address": "102.89.113.61",
      "avatar": "https://robohash.org/ducimusmagnamaliquam.png?size=318x180&set=set1"
    }, {
      "id": 15,
      "first_name": "Steven",
      "last_name": "Edwards",
      "email": "sedwardse@businessweek.com",
      "gender": "Male",
      "ip_address": "190.233.13.64",
      "avatar": "https://robohash.org/eteiusiste.png?size=318x180&set=set1"
    }, {
      "id": 16,
      "first_name": "Frank",
      "last_name": "Nguyen",
      "email": "fnguyenf@imgur.com",
      "gender": "Male",
      "ip_address": "254.24.117.39",
      "avatar": "https://robohash.org/minusutnesciunt.png?size=318x180&set=set1"
    }, {
      "id": 17,
      "first_name": "Julie",
      "last_name": "Gonzalez",
      "email": "jgonzalezg@biblegateway.com",
      "gender": "Female",
      "ip_address": "82.84.202.207",
      "avatar": "https://robohash.org/quasiveliusto.png?size=318x180&set=set1"
    }, {
      "id": 18,
      "first_name": "Pamela",
      "last_name": "Garcia",
      "email": "pgarciah@reuters.com",
      "gender": "Female",
      "ip_address": "44.33.254.166",
      "avatar": "https://robohash.org/atabincidunt.png?size=318x180&set=set1"
    }, {
      "id": 19,
      "first_name": "Ralph",
      "last_name": "Reyes",
      "email": "rreyesi@qq.com",
      "gender": "Male",
      "ip_address": "159.131.148.160",
      "avatar": "https://robohash.org/magnamdeseruntexercitationem.png?size=318x180&set=set1"
    }, {
      "id": 20,
      "first_name": "Andrea",
      "last_name": "Hamilton",
      "email": "ahamiltonj@jiathis.com",
      "gender": "Female",
      "ip_address": "92.23.141.96",
      "avatar": "https://robohash.org/etdoloribusfacilis.png?size=318x180&set=set1"
    }, {
      "id": 21,
      "first_name": "John",
      "last_name": "Fields",
      "email": "jfieldsk@businessinsider.com",
      "gender": "Male",
      "ip_address": "220.235.141.121",
      "avatar": "https://robohash.org/etullamet.png?size=318x180&set=set1"
    }, {
      "id": 22,
      "first_name": "Rachel",
      "last_name": "Ferguson",
      "email": "rfergusonl@trellian.com",
      "gender": "Female",
      "ip_address": "170.1.14.233",
      "avatar": "https://robohash.org/officiisvoluptateiste.png?size=318x180&set=set1"
    }, {
      "id": 23,
      "first_name": "William",
      "last_name": "Harrison",
      "email": "wharrisonm@angelfire.com",
      "gender": "Male",
      "ip_address": "52.19.223.216",
      "avatar": "https://robohash.org/voluptaseumquia.png?size=318x180&set=set1"
    }, {
      "id": 24,
      "first_name": "Virginia",
      "last_name": "Hall",
      "email": "vhalln@indiatimes.com",
      "gender": "Female",
      "ip_address": "221.242.160.81",
      "avatar": "https://robohash.org/aspernaturfugitmolestias.png?size=318x180&set=set1"
    }, {
      "id": 25,
      "first_name": "Douglas",
      "last_name": "Carter",
      "email": "dcartero@columbia.edu",
      "gender": "Male",
      "ip_address": "14.136.99.47",
      "avatar": "https://robohash.org/quissintporro.png?size=318x180&set=set1"
    }, {
      "id": 26,
      "first_name": "Julie",
      "last_name": "Murphy",
      "email": "jmurphyp@yellowbook.com",
      "gender": "Female",
      "ip_address": "224.33.142.61",
      "avatar": "https://robohash.org/sedporroarchitecto.png?size=318x180&set=set1"
    }, {
      "id": 27,
      "first_name": "Eric",
      "last_name": "Johnston",
      "email": "ejohnstonq@pagesperso-orange.fr",
      "gender": "Male",
      "ip_address": "81.49.41.121",
      "avatar": "https://robohash.org/voluptatemomnissint.png?size=318x180&set=set1"
    }, {
      "id": 28,
      "first_name": "Antonio",
      "last_name": "Willis",
      "email": "awillisr@chron.com",
      "gender": "Male",
      "ip_address": "36.239.223.15",
      "avatar": "https://robohash.org/debitisconsequaturmolestiae.png?size=318x180&set=set1"
    }, {
      "id": 29,
      "first_name": "Steve",
      "last_name": "Romero",
      "email": "sromeros@miibeian.gov.cn",
      "gender": "Male",
      "ip_address": "111.114.123.174",
      "avatar": "https://robohash.org/voluptatemautaut.png?size=318x180&set=set1"
    }, {
      "id": 30,
      "first_name": "Mark",
      "last_name": "Chapman",
      "email": "mchapmant@youtube.com",
      "gender": "Male",
      "ip_address": "72.114.121.200",
      "avatar": "https://robohash.org/etfugitomnis.png?size=318x180&set=set1"
    }, {
      "id": 31,
      "first_name": "Nancy",
      "last_name": "Turner",
      "email": "nturneru@smh.com.au",
      "gender": "Female",
      "ip_address": "204.106.210.50",
      "avatar": "https://robohash.org/quieumquos.png?size=318x180&set=set1"
    }, {
      "id": 32,
      "first_name": "Donald",
      "last_name": "Simmons",
      "email": "dsimmonsv@1688.com",
      "gender": "Male",
      "ip_address": "187.85.126.204",
      "avatar": "https://robohash.org/blanditiissuntet.png?size=318x180&set=set1"
    }, {
      "id": 33,
      "first_name": "Lillian",
      "last_name": "Gonzalez",
      "email": "lgonzalezw@yahoo.com",
      "gender": "Female",
      "ip_address": "63.169.247.215",
      "avatar": "https://robohash.org/ipsaetin.png?size=318x180&set=set1"
    }, {
      "id": 34,
      "first_name": "Craig",
      "last_name": "Lewis",
      "email": "clewisx@deliciousdays.com",
      "gender": "Male",
      "ip_address": "13.17.136.206",
      "avatar": "https://robohash.org/minimasuntnecessitatibus.png?size=318x180&set=set1"
    }, {
      "id": 35,
      "first_name": "Linda",
      "last_name": "Dixon",
      "email": "ldixony@loc.gov",
      "gender": "Female",
      "ip_address": "221.32.1.38",
      "avatar": "https://robohash.org/evenietearumqui.png?size=318x180&set=set1"
    }, {
      "id": 36,
      "first_name": "Charles",
      "last_name": "Rogers",
      "email": "crogersz@mysql.com",
      "gender": "Male",
      "ip_address": "107.182.126.123",
      "avatar": "https://robohash.org/atliberout.png?size=318x180&set=set1"
    }, {
      "id": 37,
      "first_name": "Judy",
      "last_name": "Black",
      "email": "jblack10@jimdo.com",
      "gender": "Female",
      "ip_address": "36.179.15.42",
      "avatar": "https://robohash.org/dolorutdoloremque.png?size=318x180&set=set1"
    }, {
      "id": 38,
      "first_name": "Keith",
      "last_name": "Alvarez",
      "email": "kalvarez11@canalblog.com",
      "gender": "Male",
      "ip_address": "86.227.112.100",
      "avatar": "https://robohash.org/providentexercitationemomnis.png?size=318x180&set=set1"
    }, {
      "id": 39,
      "first_name": "Bruce",
      "last_name": "Thomas",
      "email": "bthomas12@tuttocitta.it",
      "gender": "Male",
      "ip_address": "181.172.46.86",
      "avatar": "https://robohash.org/ineoset.png?size=318x180&set=set1"
    }, {
      "id": 40,
      "first_name": "Lillian",
      "last_name": "Wells",
      "email": "lwells13@yolasite.com",
      "gender": "Female",
      "ip_address": "74.108.100.137",
      "avatar": "https://robohash.org/oditperspiciatisdebitis.png?size=318x180&set=set1"
    }, {
      "id": 41,
      "first_name": "Michael",
      "last_name": "Diaz",
      "email": "mdiaz14@dailymotion.com",
      "gender": "Male",
      "ip_address": "35.71.251.14",
      "avatar": "https://robohash.org/consecteturverovoluptatem.png?size=318x180&set=set1"
    }, {
      "id": 42,
      "first_name": "Melissa",
      "last_name": "Lopez",
      "email": "mlopez15@canalblog.com",
      "gender": "Female",
      "ip_address": "77.60.93.146",
      "avatar": "https://robohash.org/rerumdoloremaiores.png?size=318x180&set=set1"
    }, {
      "id": 43,
      "first_name": "Sandra",
      "last_name": "Armstrong",
      "email": "sarmstrong16@google.es",
      "gender": "Female",
      "ip_address": "36.190.115.10",
      "avatar": "https://robohash.org/suntatmollitia.png?size=318x180&set=set1"
    }, {
      "id": 44,
      "first_name": "Marilyn",
      "last_name": "Smith",
      "email": "msmith17@apache.org",
      "gender": "Female",
      "ip_address": "231.239.12.72",
      "avatar": "https://robohash.org/itaquemolestiaeautem.png?size=318x180&set=set1"
    }, {
      "id": 45,
      "first_name": "Donna",
      "last_name": "Cox",
      "email": "dcox18@house.gov",
      "gender": "Female",
      "ip_address": "117.138.206.162",
      "avatar": "https://robohash.org/quiculpasint.png?size=318x180&set=set1"
    }, {
      "id": 46,
      "first_name": "Norma",
      "last_name": "Washington",
      "email": "nwashington19@xing.com",
      "gender": "Female",
      "ip_address": "200.42.220.215",
      "avatar": "https://robohash.org/sintetveritatis.png?size=318x180&set=set1"
    }, {
      "id": 47,
      "first_name": "Joe",
      "last_name": "Hudson",
      "email": "jhudson1a@google.com",
      "gender": "Male",
      "ip_address": "130.129.41.41",
      "avatar": "https://robohash.org/animiutad.png?size=318x180&set=set1"
    }, {
      "id": 48,
      "first_name": "Ann",
      "last_name": "Johnston",
      "email": "ajohnston1b@wikispaces.com",
      "gender": "Female",
      "ip_address": "87.254.137.54",
      "avatar": "https://robohash.org/intemporaet.png?size=318x180&set=set1"
    }, {
      "id": 49,
      "first_name": "Janice",
      "last_name": "Kennedy",
      "email": "jkennedy1c@theguardian.com",
      "gender": "Female",
      "ip_address": "171.82.109.176",
      "avatar": "https://robohash.org/quibusdamaliquidsint.png?size=318x180&set=set1"
    }, {
      "id": 50,
      "first_name": "Roy",
      "last_name": "Griffin",
      "email": "rgriffin1d@soundcloud.com",
      "gender": "Male",
      "ip_address": "254.216.118.249",
      "avatar": "https://robohash.org/uttotamquidem.png?size=318x180&set=set1"
    }, {
      "id": 51,
      "first_name": "Sharon",
      "last_name": "Hernandez",
      "email": "shernandez1e@paginegialle.it",
      "gender": "Female",
      "ip_address": "2.144.248.3",
      "avatar": "https://robohash.org/eosrepellatnemo.png?size=318x180&set=set1"
    }, {
      "id": 52,
      "first_name": "Kimberly",
      "last_name": "Diaz",
      "email": "kdiaz1f@topsy.com",
      "gender": "Female",
      "ip_address": "81.148.57.140",
      "avatar": "https://robohash.org/facilissequidolorem.png?size=318x180&set=set1"
    }, {
      "id": 53,
      "first_name": "Adam",
      "last_name": "Gomez",
      "email": "agomez1g@hatena.ne.jp",
      "gender": "Male",
      "ip_address": "135.94.2.32",
      "avatar": "https://robohash.org/fugitetnam.png?size=318x180&set=set1"
    }, {
      "id": 54,
      "first_name": "Margaret",
      "last_name": "Howell",
      "email": "mhowell1h@nydailynews.com",
      "gender": "Female",
      "ip_address": "24.204.96.101",
      "avatar": "https://robohash.org/sitilloest.png?size=318x180&set=set1"
    }, {
      "id": 55,
      "first_name": "Carol",
      "last_name": "Rice",
      "email": "crice1i@nasa.gov",
      "gender": "Female",
      "ip_address": "175.201.97.168",
      "avatar": "https://robohash.org/consecteturducimusqui.png?size=318x180&set=set1"
    }, {
      "id": 56,
      "first_name": "Andrew",
      "last_name": "King",
      "email": "aking1j@earthlink.net",
      "gender": "Male",
      "ip_address": "133.148.146.230",
      "avatar": "https://robohash.org/quirepellatunde.png?size=318x180&set=set1"
    }, {
      "id": 57,
      "first_name": "George",
      "last_name": "Cook",
      "email": "gcook1k@multiply.com",
      "gender": "Male",
      "ip_address": "57.103.171.135",
      "avatar": "https://robohash.org/voluptasutsed.png?size=318x180&set=set1"
    }, {
      "id": 58,
      "first_name": "Annie",
      "last_name": "Russell",
      "email": "arussell1l@linkedin.com",
      "gender": "Female",
      "ip_address": "70.89.7.188",
      "avatar": "https://robohash.org/autautofficiis.png?size=318x180&set=set1"
    }, {
      "id": 59,
      "first_name": "Christopher",
      "last_name": "Hayes",
      "email": "chayes1m@creativecommons.org",
      "gender": "Male",
      "ip_address": "88.250.199.219",
      "avatar": "https://robohash.org/etessea.png?size=318x180&set=set1"
    }, {
      "id": 60,
      "first_name": "Amy",
      "last_name": "Carpenter",
      "email": "acarpenter1n@mac.com",
      "gender": "Female",
      "ip_address": "243.86.127.36",
      "avatar": "https://robohash.org/voluptatumremsuscipit.png?size=318x180&set=set1"
    }, {
      "id": 61,
      "first_name": "Norma",
      "last_name": "Holmes",
      "email": "nholmes1o@vkontakte.ru",
      "gender": "Female",
      "ip_address": "206.91.50.117",
      "avatar": "https://robohash.org/solutaquosunt.png?size=318x180&set=set1"
    }, {
      "id": 62,
      "first_name": "Andrew",
      "last_name": "Torres",
      "email": "atorres1p@goo.ne.jp",
      "gender": "Male",
      "ip_address": "73.148.231.53",
      "avatar": "https://robohash.org/velessemollitia.png?size=318x180&set=set1"
    }, {
      "id": 63,
      "first_name": "Peter",
      "last_name": "Smith",
      "email": "psmith1q@plala.or.jp",
      "gender": "Male",
      "ip_address": "87.148.20.251",
      "avatar": "https://robohash.org/molestiaeeavoluptas.png?size=318x180&set=set1"
    }, {
      "id": 64,
      "first_name": "Andrea",
      "last_name": "Hill",
      "email": "ahill1r@unesco.org",
      "gender": "Female",
      "ip_address": "29.150.129.172",
      "avatar": "https://robohash.org/deseruntquaenam.png?size=318x180&set=set1"
    }, {
      "id": 65,
      "first_name": "Wayne",
      "last_name": "Garcia",
      "email": "wgarcia1s@cnn.com",
      "gender": "Male",
      "ip_address": "57.122.78.97",
      "avatar": "https://robohash.org/architectorerumodio.png?size=318x180&set=set1"
    }, {
      "id": 66,
      "first_name": "Doris",
      "last_name": "Fox",
      "email": "dfox1t@blogs.com",
      "gender": "Female",
      "ip_address": "98.41.135.181",
      "avatar": "https://robohash.org/nesciuntdeseruntminima.png?size=318x180&set=set1"
    }, {
      "id": 67,
      "first_name": "Tammy",
      "last_name": "Ruiz",
      "email": "truiz1u@reverbnation.com",
      "gender": "Female",
      "ip_address": "150.17.77.138",
      "avatar": "https://robohash.org/estearumperferendis.png?size=318x180&set=set1"
    }, {
      "id": 68,
      "first_name": "Janice",
      "last_name": "Green",
      "email": "jgreen1v@purevolume.com",
      "gender": "Female",
      "ip_address": "159.183.209.155",
      "avatar": "https://robohash.org/incorruptidolore.png?size=318x180&set=set1"
    }, {
      "id": 69,
      "first_name": "Phyllis",
      "last_name": "Wheeler",
      "email": "pwheeler1w@smugmug.com",
      "gender": "Female",
      "ip_address": "177.156.212.195",
      "avatar": "https://robohash.org/atqueatfacere.png?size=318x180&set=set1"
    }, {
      "id": 70,
      "first_name": "Eugene",
      "last_name": "Bowman",
      "email": "ebowman1x@mayoclinic.com",
      "gender": "Male",
      "ip_address": "40.188.108.176",
      "avatar": "https://robohash.org/faceredoloremut.png?size=318x180&set=set1"
    }, {
      "id": 71,
      "first_name": "Anna",
      "last_name": "Flores",
      "email": "aflores1y@census.gov",
      "gender": "Female",
      "ip_address": "143.60.238.36",
      "avatar": "https://robohash.org/voluptatemollitiaperferendis.png?size=318x180&set=set1"
    }, {
      "id": 72,
      "first_name": "Roger",
      "last_name": "Kelly",
      "email": "rkelly1z@fc2.com",
      "gender": "Male",
      "ip_address": "158.16.108.244",
      "avatar": "https://robohash.org/quaenesciuntculpa.png?size=318x180&set=set1"
    }, {
      "id": 73,
      "first_name": "Marilyn",
      "last_name": "Hanson",
      "email": "mhanson20@scribd.com",
      "gender": "Female",
      "ip_address": "159.11.253.198",
      "avatar": "https://robohash.org/possimusfaceresit.png?size=318x180&set=set1"
    }, {
      "id": 74,
      "first_name": "Jerry",
      "last_name": "Mendoza",
      "email": "jmendoza21@cbslocal.com",
      "gender": "Male",
      "ip_address": "240.172.93.197",
      "avatar": "https://robohash.org/facilisetest.png?size=318x180&set=set1"
    }, {
      "id": 75,
      "first_name": "Adam",
      "last_name": "Garza",
      "email": "agarza22@springer.com",
      "gender": "Male",
      "ip_address": "81.75.113.251",
      "avatar": "https://robohash.org/quisnequelaudantium.png?size=318x180&set=set1"
    }, {
      "id": 76,
      "first_name": "Joshua",
      "last_name": "Clark",
      "email": "jclark23@devhub.com",
      "gender": "Male",
      "ip_address": "248.155.133.79",
      "avatar": "https://robohash.org/adipisciminimanobis.png?size=318x180&set=set1"
    }, {
      "id": 77,
      "first_name": "Robert",
      "last_name": "Patterson",
      "email": "rpatterson24@irs.gov",
      "gender": "Male",
      "ip_address": "134.82.219.2",
      "avatar": "https://robohash.org/aliquidtemporibuset.png?size=318x180&set=set1"
    }, {
      "id": 78,
      "first_name": "Michelle",
      "last_name": "Simmons",
      "email": "msimmons25@webmd.com",
      "gender": "Female",
      "ip_address": "161.166.94.131",
      "avatar": "https://robohash.org/etquoet.png?size=318x180&set=set1"
    }, {
      "id": 79,
      "first_name": "Joan",
      "last_name": "Marshall",
      "email": "jmarshall26@g.co",
      "gender": "Female",
      "ip_address": "3.233.235.32",
      "avatar": "https://robohash.org/fugitmolestiasmaxime.png?size=318x180&set=set1"
    }, {
      "id": 80,
      "first_name": "Gloria",
      "last_name": "Gordon",
      "email": "ggordon27@prlog.org",
      "gender": "Female",
      "ip_address": "190.41.244.213",
      "avatar": "https://robohash.org/isteculpanon.png?size=318x180&set=set1"
    }, {
      "id": 81,
      "first_name": "Patricia",
      "last_name": "Brown",
      "email": "pbrown28@howstuffworks.com",
      "gender": "Female",
      "ip_address": "105.35.236.216",
      "avatar": "https://robohash.org/eaqueexcepturisoluta.png?size=318x180&set=set1"
    }, {
      "id": 82,
      "first_name": "Larry",
      "last_name": "Fernandez",
      "email": "lfernandez29@miibeian.gov.cn",
      "gender": "Male",
      "ip_address": "81.17.114.79",
      "avatar": "https://robohash.org/seddoloremanimi.png?size=318x180&set=set1"
    }, {
      "id": 83,
      "first_name": "Jack",
      "last_name": "Hernandez",
      "email": "jhernandez2a@hubpages.com",
      "gender": "Male",
      "ip_address": "132.101.164.177",
      "avatar": "https://robohash.org/atconsequaturvoluptatem.png?size=318x180&set=set1"
    }, {
      "id": 84,
      "first_name": "Mildred",
      "last_name": "Hansen",
      "email": "mhansen2b@php.net",
      "gender": "Female",
      "ip_address": "46.73.247.19",
      "avatar": "https://robohash.org/eossaepequi.png?size=318x180&set=set1"
    }, {
      "id": 85,
      "first_name": "Lawrence",
      "last_name": "Taylor",
      "email": "ltaylor2c@theatlantic.com",
      "gender": "Male",
      "ip_address": "64.183.119.26",
      "avatar": "https://robohash.org/illoquoest.png?size=318x180&set=set1"
    }, {
      "id": 86,
      "first_name": "Joe",
      "last_name": "Moreno",
      "email": "jmoreno2d@dailymotion.com",
      "gender": "Male",
      "ip_address": "229.165.169.184",
      "avatar": "https://robohash.org/modibeataeexpedita.png?size=318x180&set=set1"
    }, {
      "id": 87,
      "first_name": "Rose",
      "last_name": "Ortiz",
      "email": "rortiz2e@microsoft.com",
      "gender": "Female",
      "ip_address": "62.104.129.15",
      "avatar": "https://robohash.org/consequaturveritatiscommodi.png?size=318x180&set=set1"
    }, {
      "id": 88,
      "first_name": "David",
      "last_name": "Wheeler",
      "email": "dwheeler2f@google.de",
      "gender": "Male",
      "ip_address": "152.253.20.155",
      "avatar": "https://robohash.org/voluptasmagnamrem.png?size=318x180&set=set1"
    }, {
      "id": 89,
      "first_name": "Edward",
      "last_name": "Young",
      "email": "eyoung2g@forbes.com",
      "gender": "Male",
      "ip_address": "187.230.243.182",
      "avatar": "https://robohash.org/similiqueullamexplicabo.png?size=318x180&set=set1"
    }, {
      "id": 90,
      "first_name": "Donna",
      "last_name": "Elliott",
      "email": "delliott2h@hubpages.com",
      "gender": "Female",
      "ip_address": "188.11.96.58",
      "avatar": "https://robohash.org/utabdeserunt.png?size=318x180&set=set1"
    }, {
      "id": 91,
      "first_name": "Ryan",
      "last_name": "Grant",
      "email": "rgrant2i@umn.edu",
      "gender": "Male",
      "ip_address": "249.138.127.136",
      "avatar": "https://robohash.org/molestiasetsed.png?size=318x180&set=set1"
    }, {
      "id": 92,
      "first_name": "Ashley",
      "last_name": "Ortiz",
      "email": "aortiz2j@va.gov",
      "gender": "Female",
      "ip_address": "183.12.235.142",
      "avatar": "https://robohash.org/voluptatemetodio.png?size=318x180&set=set1"
    }, {
      "id": 93,
      "first_name": "Shirley",
      "last_name": "Rodriguez",
      "email": "srodriguez2k@google.com.br",
      "gender": "Female",
      "ip_address": "42.104.125.147",
      "avatar": "https://robohash.org/assumendarerumconsequatur.png?size=318x180&set=set1"
    }, {
      "id": 94,
      "first_name": "Virginia",
      "last_name": "Rivera",
      "email": "vrivera2l@webnode.com",
      "gender": "Female",
      "ip_address": "177.74.39.40",
      "avatar": "https://robohash.org/optiorepellatnobis.png?size=318x180&set=set1"
    }, {
      "id": 95,
      "first_name": "Dennis",
      "last_name": "Palmer",
      "email": "dpalmer2m@rakuten.co.jp",
      "gender": "Male",
      "ip_address": "255.223.73.50",
      "avatar": "https://robohash.org/illorepellendusfacere.png?size=318x180&set=set1"
    }, {
      "id": 96,
      "first_name": "Wayne",
      "last_name": "Martin",
      "email": "wmartin2n@chron.com",
      "gender": "Male",
      "ip_address": "30.237.14.217",
      "avatar": "https://robohash.org/expeditaquaseius.png?size=318x180&set=set1"
    }, {
      "id": 97,
      "first_name": "Brian",
      "last_name": "Ross",
      "email": "bross2o@g.co",
      "gender": "Male",
      "ip_address": "60.74.171.18",
      "avatar": "https://robohash.org/atqueinquis.png?size=318x180&set=set1"
    }, {
      "id": 98,
      "first_name": "Judy",
      "last_name": "Peterson",
      "email": "jpeterson2p@nps.gov",
      "gender": "Female",
      "ip_address": "149.6.35.198",
      "avatar": "https://robohash.org/numquamrationeneque.png?size=318x180&set=set1"
    }, {
      "id": 99,
      "first_name": "Sean",
      "last_name": "Jones",
      "email": "sjones2q@wired.com",
      "gender": "Male",
      "ip_address": "251.218.193.125",
      "avatar": "https://robohash.org/quiarchitectomagnam.png?size=318x180&set=set1"
    }, {
      "id": 100,
      "first_name": "Howard",
      "last_name": "Burton",
      "email": "hburton2r@un.org",
      "gender": "Male",
      "ip_address": "37.237.9.92",
      "avatar": "https://robohash.org/officiatotamet.png?size=318x180&set=set1"
    }],
    searchQuery: '',
    maxResults: 10,
    chunk: [],
    counter: 0,
    numbers: []
  },
  created: function() {
    this.chunk = _.chunk(this.mockUsers, this.maxResults);
    this.mockUsers = this.chunk[this.counter];
    for (var i = 0; i < this.mockUsers.length; i++) {
      this.numbers[i] = i;
    }
  },
  methods: {
    next: function() {
      this.counter++;
      if (this.counter >= this.mockUsers.length) {
        this.counter = 0;
        this.mockUsers = this.chunk[this.counter];
      } else {
        this.mockUsers = this.chunk[this.counter];
      }
    },
    prev: function() {
      this.counter--;
      if (this.counter < 0) {
        this.counter = this.mockUsers.length - 1;
        this.mockUsers = this.chunk[this.counter];
      } else {
        this.mockUsers = this.chunk[this.counter];
      }
    },
    page: function(num) {
      this.counter = num;
      this.mockUsers = this.chunk[num];
    }
  },
  computed: {
    cUsers: function() {
      return _.filter(this.mockUsers, (user) => {
        return _.includes(user.first_name.toLowerCase(), this.searchQuery.toLowerCase()) ||
          _.includes(user.last_name.toLowerCase(), this.searchQuery.toLowerCase()) ||
          _.includes(user.email.toLowerCase(), this.searchQuery.toLowerCase()) ||
          _.includes(user.first_name.toLowerCase() + ' ' + user.last_name.toLowerCase(), this.searchQuery.toLowerCase())
      })
    }
  }
})
